# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Training Course on Galaxy for Bioinformatics tool developers
tagline:             Training Course on Galaxy for Bioinformatics tool developers
description:         Galaxy4Developers
url:                 'https://crs4.github.io/Galaxy4Developers'
baseurl:             'Galaxy4Developers'
twitter_username:
github_username:  crs4
pages_url: https://crs4.github.io/Galaxy4Developers
github_url: https://github.com/crs4/Galaxy4Developers

# Custom vars
version:             17.07

# Build settings
markdown: kramdown
